version: "3"

x-tina4-jobs-common-variables:
  &tina4-jobs-common-variables
  BASE_URL: 'http://localhost:7145'
  REDIS_HOST: redis
  REDIS_PORT: 6379
  DEFAULT_USER_TOKEN_EXPIRY_DAYS: 1
  TINA4_SERVICE_TIME: 60

services:
  app:
    container_name: tina4_jobs
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      <<: *tina4-jobs-common-variables
    ports:
      - "9800:7145"
    volumes:
      - ../:/var/www/html
    networks:
      - internal

  jobs:
    container_name: tina4_jobs_jobs
    build:
      context: ./
      dockerfile: Dockerfile-jobs
    environment:
      <<: *tina4-jobs-common-variables
    volumes:
      - ../:/var/www/html
    networks:
      - internal
    depends_on:
      - redis
      - kafka

  kafka:
    container_name: tina4_jobs_kafka
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENER: INSIDE_KAFKA:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME: INSIDE_KAFKA
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_INTERNAL: INSIDE_KAFKA
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE_KAFKA
    depends_on:
      - zookeeper
    networks:
      - internal


  zookeeper:
    image: wurstmeister/zookeeper:latest
    networks:
      - internal


  redis:
    container_name: tina4_jobs_redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - tina4-jobs-redis-data:/data
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  tina4-jobs-db-data:
  tina4-jobs-redis-data:


