version: "3"

x-tina4-jobs-common-variables:
  &tina4-jobs-common-variables
  BASE_URL: 'http://localhost:7145'
  REDIS_HOST: redis
  REDIS_PORT: 6379
  DEFAULT_USER_TOKEN_EXPIRY_DAYS: 1
  TINA4_SERVICE_TIME: 60

services:
  app:
    container_name: tina4_jobs
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      <<: *tina4-jobs-common-variables
    ports:
      - "9000:7145"
    volumes:
      - ../:/var/www/html
    networks:
      - internal
  jobs:
    container_name: tina4_jobs_jobs
    build:
      context: ./
      dockerfile: Dockerfile-jobs
    environment:
      <<: *tina4-jobs-common-variables
    volumes:
      - ../:/var/www/html
    networks:
      - internal
    depends_on:
      - redis
  redis:
    container_name: tina4_jobs_redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - tina4-jobs-redis-data:/data
    networks:
      - internal

networks:
  internal:

volumes:
  tina4-jobs-db-data:
  tina4-jobs-redis-data:


